[package]
name = "kfc-bot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serenity = "0.10.8"
tokio = { version = "1.7.0", features = ["full"] }
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
